steps: 

#Execute SAST Scan using SonarCloud in GCP DevSecOps Pipeline
  - name: 'maven:3.9-eclipse-temurin-17'
    entrypoint: 'mvn'
    args:
      - 'verify'
      - 'sonar:sonar'
      - '-Dsonar.host.url=https://sonarcloud.io'
      - '-Dsonar.organization=krmdev'
      - '-Dsonar.projectKey=rifkikarimr_java-n2n-devsecops-pipeline'
      - '-Dsonar.token=${_SONAR_TOKEN}'
    id: 'SAST Scan using SonarCloud'

#Run Software Composition Analysis (SCA security scan) using Snyk in GCP DevSecOps Pipeline
  - name: 'ubuntu'
    entrypoint: bash
    args: 
        - '-c'
        - |-
          apt-get update
          apt-get -y install maven 
          SNYK_TOKEN=${_SNYK_TOKEN}
          export SNYK_TOKEN
          mvn snyk:test -fn -Dsnyk.jsonOutputFile=snyk_report.json
    id: SCA Scan using Snyk in GCP DevSecOps Pipeline

#Run DAST scan using OWASP ZAP in GCP DevSecOps Pipeline
  - name: 'ubuntu'
    entrypoint: bash
    args: 
      - '-c'
      - |-
        apt-get update
        apt-get -y install wget
        apt-get -y install default-jdk
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.16.0/ZAP_2.16.0_Linux.tar.gz
        tar -xvf ZAP_2.16.0_Linux.tar.gz
        cd ZAP_2.16.0
        ./zap.sh -cmd -quickurl https://samudera.id -quickprogress -quickout ../zap_report.html -quickout ../zap_report.json
    id: DAST Scan using OWASP ZAP in GCP DevSecOps Pipeline

  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |-
        pip install google-generativeai
        python summarize_reports.py
    # Mengambil API Key dari Secret Manager
    secretEnv: ['GEMINI_API_KEY']
    id: 'AI Security Summary'

#Store Reports Generated by OWASP ZAP in GCP Cloud Bucket named ASecurityGuru
artifacts:
  objects:
    location: 'gs://java-devsecops-pipeline'
    paths:
      - 'zap_report.html'
      - 'zap_report.json'
      - 'snyk_report.json'

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/GEMINI_API_KEY/versions/latest
    env: 'GEMINI_API_KEY'

options:
  logging: CLOUD_LOGGING_ONLY
  
