steps:
  # Langkah ini HANYA untuk menguji izin akses ke Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |-
        echo "===================================================="
        echo "Menjalankan tes sebagai Service Account Cloud Build..."
        echo "Mencoba mengakses secret 'GEMINI_API_KEY' di proyek '${PROJECT_ID}'..."
        
        # Perintah ini mencoba membaca secret. Jika berhasil, izin sudah benar.
        # Jika gagal dengan 'PermissionDenied', izin masih salah.
        gcloud secrets versions access latest --secret="GEMINI_API_KEY" --project="${PROJECT_ID}"
        
        echo "===================================================="
        echo "Jika Anda melihat isi secret (serangkaian karakter acak) di atas, maka izin SUDAH BENAR."
        echo "Jika Anda melihat error 'PermissionDenied', maka izin MASIH SALAH."
        echo "===================================================="
    id: 'Definitive IAM Permission Test'

options:
  logging: CLOUD_LOGGING_ONLY