steps:
  # LANGKAH 1: CETAK VARIABEL UNTUK DEBUGGING
  # Langkah ini akan menunjukkan nilai apa yang sebenarnya diterima oleh Cloud Build.
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |-
        echo "============================================================"
        echo "MEMERIKSA VARIABEL YANG DITERIMA BUILD:"
        echo "ORGANISASI UNTUK DIVERIFIKASI: ${_SNYK_ORG}"
        echo "AWALAN TOKEN UNTUK DIVERIFIKASI: $(echo ${_SNYK_TOKEN} | cut -c 1-8)..."
        echo "============================================================"
    id: 'Debug Variables'

  # LANGKAH 2: TES OTENTIKASI SNYK SECARA LANGSUNG
  # Menggunakan image resmi Snyk CLI yang lebih sederhana untuk tes.
  - name: 'snyk/snyk:maven'
    entrypoint: 'snyk'
    args:
      - 'test'
      - '--org=rifkikarimr'
    env:
      - 'SNYK_TOKEN=${_SNYK_TOKEN}'
    id: 'Direct Snyk Auth Test'

options:
  logging: CLOUD_LOGGING_ONLY